version: 2
before:
  hooks:
    - go mod tidy
builds:
  - id: webhook-go
    binary: webhook-go
    env:
      - CGO_ENABLED=0
    main: .
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -trimpath
    ldflags:
      - -s -w
archives:
  - format: binary
    name_template: "{{ .Binary }}_{{ .Os  }}_{{ .Arch }}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  use: github-native
nfpms:
  - id: default
    package_name: webhook-go
    homepage: https://github.com/ustclug-dev/webhook-go
    maintainer: "iBug <i@ibugone.com>"
    description: |-
      A simple webhook for GitHub events
    formats:
      - deb
    umask: 0o022
    section: admin
    priority: extra
    scripts:
      postinstall: etc/postinst.sh
      preremove: etc/prerm.sh
    contents:
      - src: README.md
        dst: /usr/share/doc/webhook-go/
      - src: etc/config.yml
        dst: /etc/webhook-go/config.example.yml
      - src: etc/webhook-go.service
        dst: /lib/systemd/system/


# modelines, feel free to remove those if you don't want/use them:
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
