name: Go build and release

on:
  - push
  - pull_request

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      NAME: webhook-go
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17

    - name: Build
      run: go build -ldflags='-s -w' -v ./...

    - name: Deploy - Create Release
      if: startsWith(github.ref, 'refs/tags/')
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: ${{ github.ref_name }}
        draft: false
        prerelease: false

    - name: Deploy - Upload Release
      if: startsWith(github.ref, 'refs/tags/')
      id: upload-release-asset 
      uses: csexton/release-asset-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        release-url: ${{ steps.create_release.outputs.upload_url }}
        pattern: ${{ env.NAME }}
